language: node_js

node_js: '10'

script:
  - npm test

cache:
  directories:
    - $HOME/.npm

jobs:
  include:
    - stage: release
      language: node_js
      node_js: '10'
      script:
        - npm run release

stages:
  - name: release
    if: branch = master AND type = push AND fork = false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
